#ifndef PEDALINATOR_CONFIG_H
#define PEDALINATOR_CONFIG_H

// #define TAU (((double)CORPO_L) / 15.0)

// #define TEST_SWITCH
// #define TEST_INTERRUPTS
// #define TEST_TIMER
// #define PEDALINATOR_PITCH_MODULATION
// #define PEDALINATOR_ALL_NOTES_STORED
// #define PEDALINATOR_ADVANCED_PITCH_MODULATION
// #define PEDALINATOR_HSAI_IT
// #define PEDALINATOR_FOUR_SIMPLE_NOTES_WITH_DMA
#define PEDALINATOR_DEFINITIVE_FOUR_NOTES_WITH_DMA
// #define PEDALINATOR_COM_VIRTUAL_PORT_EXAMPLE

#if defined(PEDALINATOR_DEFINITIVE_FOUR_NOTES_WITH_DMA)
#define C_ATTACCO_MAX_L (50000U)
#define C_CORPO_MAX_L   (50000U)
#define C_DECAY_MAX_L   (50000U)
#define CURRENT_NOTE_L  (50000U)
#endif

#ifdef PEDALINATOR_ALL_NOTES_STORED
#define PEDALINATOR_N_NOTES 8
#endif  // PEDALINATOR_ALL_NOTES_STORED

#ifdef PEDALINATOR_PITCH_MODULATION

#define SEMITONE_RATIO (1.0594630943592953L)
#define MAX_LEN_MUL    (3U)

#define BASE_ATTACCO_L      (SAMPLE_22KHZ5_LOOP_POINT)
#define BASE_CORPO_L        ((SAMPLE_22KHZ5_SIZE - SAMPLE_22KHZ5_LOOP_POINT) * 2)
#define BASE_DECAY_L        (BASE_CORPO_L / 2)
#define BASE_CURRENT_NOTE_L (SAMPLE_22KHZ5_SIZE)

#endif  // PEDALINATOR_PITCH_MODULATION

#if 0
#define MAX_ATTACCO_L      (15000U)
#define MAX_CORPO_L        (45000U)
#define MAX_DECAY_L        (20000U)
#define MAX_CURRENT_NOTE_L (60000U)
#endif

#endif  // PEDALINATOR_CONFIG_H
